### ISSUE TITLE
Modules in kernelsu doesn't install

### ISSUE THREAD

**Issue by DiamivaeBro** [QKIvan/android_kernel_google_redbull#3]
Using build from GitHub Actions 

Screenshot 
![Screenshot_20240324-172312_KernelSU](https://github.com/QKIvan/android_kernel_google_redbull/assets/119186976/b4f6a9ce-8fca-4c73-9771-ef1e6c52e61a)

KSU Logs
[KernelSU_bugreport_2024-03-24_17_17.tar.gz](https://github.com/QKIvan/android_kernel_google_redbull/files/14735742/KernelSU_bugreport_2024-03-24_17_17.tar.gz)

Device:Redfin
ROM: Linage Os 21-240318

**Comment by QKIvan** [comment]
emmm have you tried turning off overlayfs? (btw, what modules are you installing, can you send them along)
In Actions, use the source from Google (only KernelSU is turned on) and for vintf builds
I've been using the source from the Umaru Branch (by referring to kernelsu.org and turning on the configuration below) (Why not use the source from this branch in Actions? Because the changes I've made don't go through Google's vintf) and they seem to work fine!
```CONFIG_KPROBES=y
CONFIG_HAVE_KPROBES=y
CONFIG_KPROBE_EVENTS=y```
Unlike in Actions, where I also have overlayfs turned on.

**Comment by QKIvan** [comment]
btw,how did you flush this this kernel (because a lot of people have said that this kernel won't start on their phones LOL, not sure if it's a vbmeta issue)

**Comment by QKIvan** [comment]
Ref: https://github.com/QKIvan/android_kernel_google_redbull/commit/410ddab520925e3f302e25937649788644c9d19a

You can have a try.

**Comment by QKIvan** [comment]
As well as, you can likewise likewise attempt this Actions: https://github.com/Shinhubzhu/kernelsu_pixel5-Redfin--action/blob/main/.github/workflows/main.yml

They've made some changes to the kernel source to make KernelSU work on Overlayfs/Kprobes corrupted devices, I tried it a long time ago, but it looks like there are some issues in the redbull Android14 source (it looks like it only works in Android13, and rmdn tells me that the Kprobes in Android14 source is working fine).

**Comment by QKIvan** [comment]
Ref: https://github.com/QKIvan/android_kernel_google_redbull/commit/ef2a51d23af1bb3800a13c0953d0e60ff7ccdc09  
I will close this issue,thanks your help!
